algoritmo "quest01"
// Disciplina   : UC9 DESENVOLVER  ALGORITMOS 
// Professor   : Rodrigo Neves Ottoboni Dias 
// Função : Mostrar na tela  a mensagem "Olá Mundo!"
// Autor :  Rodrigo Neves Ottoboni Dias
// Data : 19/05/2025
// Lista de Exercícios do Curso Em Video - Prof: Gustavo Guanabara
var

inicio
//Comando de saída "escreva". Para mostar mensagem na tela.
escreva ("Olá Mundo!")
fimalgoritmo
